<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Community.Protocol/Community.Protocol.csproj" />
    <ProjectReference Include="../../src/Community.Server/Community.Server.csproj" />
    <ProjectReference Include="../../src/Community.Client/Community.Client.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
